name: CI
on:
  push:
    branches:
      - main
      - 'release/**'

jobs:
  dependency-validation:
    name: Dependency Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: none, ctype, dom, mbstring, phar, tokenizer, xml, xmlwriter
          coverage: none

      - name: Ensure that composer.json is valid
        run: composer validate --no-ansi --strict composer.json

      - name: Ensure that dependencies can be installed
        run: composer install --no-ansi --dry-run
  unit-tests:
    name: Unit Tests
    needs:
      - dependency-validation
    runs-on: ${{ matrix.os }}
    env:
      PHP_EXTENSIONS: none, ctype, dom, mbstring, openssl, phar, tokenizer, xml, xmlwriter
      PHP_INI_VALUES: zend.assertions=1, error_reporting=-1, log_errors_max_len=0, display_errors=On
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        php-version:
          - "8.3"
          - "8.4"
    steps:
      - name: Configure Git to avoid issues with line endings
        if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          ini-values: ${{ env.PHP_INI_VALUES }}

      - name: Install dependencies with Composer
        run: composer install --no-ansi --no-interaction --no-progress

      - name: Run tests with PHPUnit
        run: ./vendor/bin/phpunit tests/ --display-deprecations --display-errors
